#!/bin/sh /etc/rc.common
START=95
STOP=10
USE_PROCD=1

start_service() {
  [ -s /etc/one-minihouse-temperature/mosquitto_pub ] || return 1
  [ -s /etc/one-minihouse-temperature/identity ] || return 1
  for worker in collect publish; do
    procd_open_instance "$worker"
    procd_set_param command /usr/local/libexec/one-minihouse-temperature-mqtt "$worker"
    procd_set_param respawn 3600 5 5
    procd_set_param term_timeout 20
    procd_set_param stdout 0
    procd_set_param stderr 1
    procd_close_instance
  done
}
